name: BOE Trade Capture Report CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with: 
        submodules: true
    - name: Prepare build dir
      run: |
        mkdir build
        cd build
    - name: Generate build files using cmake
      run: cmake ..
    - name: Run make
      run: make
    - name: Run tests
      run: ./runUnitTests
    - name: Prepare ASAN build dir
      run: |
          cd ..
          mkdir build_asan
          cd build_asan
    - name: Generate ASAN build files using cmake
      run: cmake .. -DCMAKE_BUILD_TYPE=ASAN
    - name: Run make
      run: make
    - name: Run tests
      run: ./runUnitTests
    - name: Prepare USAN build dir
      run: |
          cd ..
          mkdir build_usan
          cd build_usan
    - name: Generate USAN build files using cmake
      run: cmake .. -DCMAKE_BUILD_TYPE=USAN
    - name: Run make
      run: make
    - name: Run tests
      run: ./runUnitTests
